# Coursera Capstone Notebook - Week 3 - Part 2

Importing the Packages that will be used to Scrape the Data From the Weblink

In [61]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

## 1. Importing the Table and converting it into a Pandas List

* <b>1.a</b> Using BeautifulSoup package to get the data from the weblink into a pandas data frame
* <b>1.b</b> Displaying the first 20 entries of the dataframe
* <b>1.c</b> Printing the size of the imported data frame

In [62]:
################
# 1.a and 1.b
################
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table))
Toronto_df=pd.DataFrame(df[0])
Toronto_df.head(20)

   Postcode           Borough     Neighbourhood
0       M1A      Not assigned      Not assigned
1       M2A      Not assigned      Not assigned
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M6A        North York  Lawrence Heights
6       M6A        North York    Lawrence Manor
7       M7A      Queen's Park      Not assigned
8       M8A      Not assigned      Not assigned
9       M9A      Queen's Park      Queen's Park
10      M1B       Scarborough             Rouge
11      M1B       Scarborough           Malvern
12      M2B      Not assigned      Not assigned
13      M3B        North York   Don Mills North
14      M4B         East York  Woodbine Gardens
15      M4B         East York     Parkview Hill
16      M5B  Downtown Toronto           Ryerson
17      M5B  Downtown Toronto   Garden District
18      M6B        North York         Glencairn
19      M7B      Not assigned      Not assigned

Printing the size of the Imported Data Frame

In [63]:
################
# 1.c
################
print(Toronto_df.shape)

(287, 3)

## 2. Now Dropping the Rows in which the Borough is not assigned

* <b>2.a</b> Droping the entries in which the Borough is not assigned 
* <b>2.b</b> Displaying the first 20 entries of the new dataframe
* <b>2.c</b> Printing the size of the new dataframe

In [64]:
################
# 2.a and 2.b
################
Toronto_df=Toronto_df[Toronto_df.Borough != 'Not assigned']
Toronto_df=Toronto_df.reset_index(drop=True,inplace=False)
Toronto_df.head(20)

   Postcode           Borough     Neighbourhood
0       M3A        North York         Parkwoods
1       M4A        North York  Victoria Village
2       M5A  Downtown Toronto      Harbourfront
3       M6A        North York  Lawrence Heights
4       M6A        North York    Lawrence Manor
5       M7A      Queen's Park      Not assigned
6       M9A      Queen's Park      Queen's Park
7       M1B       Scarborough             Rouge
8       M1B       Scarborough           Malvern
9       M3B        North York   Don Mills North
10      M4B         East York  Woodbine Gardens
11      M4B         East York     Parkview Hill
12      M5B  Downtown Toronto           Ryerson
13      M5B  Downtown Toronto   Garden District
14      M6B        North York         Glencairn
15      M9B         Etobicoke        Cloverdale
16      M9B         Etobicoke         Islington
17      M9B         Etobicoke      Martin Grove
18      M9B         Etobicoke  Princess Gardens
19      M9B         Etobicoke   West Deane Park

Printing the size of the New Data Frame

In [65]:
################
# 2.c
################
print(Toronto_df.shape)

(210, 3)

## 3. Iterating through the data frame to update the Neighbourhood value incase it is 'Not assigned'

* <b>3.a</b> Using a for loop to iterate through the dataframe to update the values of the Neighbourhood if they are 'Not assigned'  
* <b>3.b</b> Displaying the first 20 entries of the updated dataframe

In [66]:
################
# 3.a and 3.b
################
for index,row in Toronto_df.iterrows():
    if (Toronto_df['Neighbourhood'][index]=='Not assigned'):
        Toronto_df['Neighbourhood'][index]=Toronto_df['Borough'][index] 
Toronto_df.head(20)

   Postcode           Borough     Neighbourhood
0       M3A        North York         Parkwoods
1       M4A        North York  Victoria Village
2       M5A  Downtown Toronto      Harbourfront
3       M6A        North York  Lawrence Heights
4       M6A        North York    Lawrence Manor
5       M7A      Queen's Park      Queen's Park
6       M9A      Queen's Park      Queen's Park
7       M1B       Scarborough             Rouge
8       M1B       Scarborough           Malvern
9       M3B        North York   Don Mills North
10      M4B         East York  Woodbine Gardens
11      M4B         East York     Parkview Hill
12      M5B  Downtown Toronto           Ryerson
13      M5B  Downtown Toronto   Garden District
14      M6B        North York         Glencairn
15      M9B         Etobicoke        Cloverdale
16      M9B         Etobicoke         Islington
17      M9B         Etobicoke      Martin Grove
18      M9B         Etobicoke  Princess Gardens
19      M9B         Etobicoke   West Deane Park

## 4. Combining the Neighbourhoods which have same postal code

* <b>4.a</b> Using groupby function to group the neighbourhoods which share the postal code
* <b>4.b</b> Displaying the first 20 entries of the updated dataframe
* <b>4.c</b> Printing the shape of the updated dataframe

In [67]:
################
# 4.a and 4.b
################
Toronto_df = Toronto_df.groupby(['Postcode', 'Borough'])['Neighbourhood'].apply(', '.join).reset_index()
Toronto_df.head(20)

   Postcode      Borough                                      Neighbourhood
0       M1B  Scarborough                                     Rouge, Malvern
1       M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2       M1E  Scarborough                  Guildwood, Morningside, West Hill
3       M1G  Scarborough                                             Woburn
4       M1H  Scarborough                                          Cedarbrae
5       M1J  Scarborough                                Scarborough Village
6       M1K  Scarborough        East Birchmount Park, Ionview, Kennedy Park
7       M1L  Scarborough                    Clairlea, Golden Mile, Oakridge
8       M1M  Scarborough    Cliffcrest, Cliffside, Scarborough Village West
9       M1N  Scarborough                        Birch Cliff, Cliffside West
10      M1P  Scarborough  Dorset Park, Scarborough Town Centre, Wexford ...
11      M1R  Scarborough                                  Maryvale, Wexford
12      M1S  Scarborough                                          Agincourt
13      M1T  Scarborough            Clarks Corners, Sullivan, Tam O'Shanter
14      M1V  Scarborough  Agincourt North, L'Amoreaux East, Milliken, St...
15      M1W  Scarborough                                    L'Amoreaux West
16      M1X  Scarborough                                        Upper Rouge
17      M2H   North York                                  Hillcrest Village
18      M2J   North York                       Fairview, Henry Farm, Oriole
19      M2K   North York                                    Bayview Village

Printing the shape of the final data frame

In [68]:
################
# 4.c
################
print(Toronto_df.shape)

(103, 3)

## 5.  Trying to find the Latitude and Longitude of the postal Codes

* <b>5.1</b> Method One: Trying Geocoder package
    * <b>5.1.a</b> Importing packages
    * <b>5.1.b</b> Calling geocoder.google
          Comments:The code got stuck in an infinite loop, Therefore importing csv file for the latitudes and longitudes.
* <b>5.2</b> Method Two:Importing CSV file
    * <b>5.2.a</b> Importing CSV file from weblink
    * <b>5.2.b</b> Preprocessing of the dataframe before merging
    * <b>5.2.c</b> Merging the two data frames
    * <b>5.2.d</b> Printing the shape of the final data frame

### 5.1 Method One:Geocoder

In [ ]:
################
# 5.1.a
################
!conda install -c conda-forge geocoder --yes
import geocoder # import geocoder

In [ ]:
################
# 5.1.b
################
# initialize your variable to None
lat_lng_coords = None

# loop until you get the coordinates
while(lat_lng_coords is None):
    g = geocoder.google('{}, Toronto, Ontario'.format('M5G'))
    lat_lng_coords = g.latlng

latitude = lat_lng_coords[0]
longitude = lat_lng_coords[1]

### 5.2 Method Two: CSV file

In [69]:
################
# 5.2.a
################
Toronto_df_latlng = pd.read_csv('http://cocl.us/Geospatial_data', index_col=0)
print ('Data read into a pandas dataframe!')

Data read into a pandas dataframe!

In [70]:
################
# 5.2.b
################
Toronto_df_latlng.columns = list(map(str, Toronto_df_latlng.columns))
Toronto_df_latlng.reset_index(level=0, inplace=True)
Toronto_df_latlng.rename(columns={'Postal Code':'Postcode'}, inplace=True)
Toronto_df_latlng.head(20)

   Postcode   Latitude  Longitude
0       M1B  43.806686 -79.194353
1       M1C  43.784535 -79.160497
2       M1E  43.763573 -79.188711
3       M1G  43.770992 -79.216917
4       M1H  43.773136 -79.239476
5       M1J  43.744734 -79.239476
6       M1K  43.727929 -79.262029
7       M1L  43.711112 -79.284577
8       M1M  43.716316 -79.239476
9       M1N  43.692657 -79.264848
10      M1P  43.757410 -79.273304
11      M1R  43.750072 -79.295849
12      M1S  43.794200 -79.262029
13      M1T  43.781638 -79.304302
14      M1V  43.815252 -79.284577
15      M1W  43.799525 -79.318389
16      M1X  43.836125 -79.205636
17      M2H  43.803762 -79.363452
18      M2J  43.778517 -79.346556
19      M2K  43.786947 -79.385975

In [71]:
################
# 5.2.c
################
Toronto = pd.merge(Toronto_df, Toronto_df_latlng, on='Postcode')
Toronto.head(20)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park, Ionview, Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Golden Mile, Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest, Cliffside, Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Dorset Park, Scarborough Town Centre, Wexford ...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849
12,M1S,Scarborough,Agincourt,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter",43.781638,-79.304302
14,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St...",43.815252,-79.284577
15,M1W,Scarborough,L'Amoreaux West,43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,43.803762,-79.363452
18,M2J,North York,"Fairview, Henry Farm, Oriole",43.778517,-79.346556
19,M2K,North York,Bayview Village,43.786947,-79.385975

In [72]:
################
# 5.2.d
################
Toronto.shape

(103, 5)